name: Build and SBOM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build
        run: |
          mkdir -p mybinaries
          go build -o mybinaries/feather ./cmd/fledge

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: feather
          path: mybinaries/feather
