name: Build, Create SBOM, and Sign
on:
  push:
    branches: [ main ]

jobs:
  build-sbom-sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build Go binary
      run: |
        go build -o fledge ./cmd/fledge

    - name: Install syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Create SBOM
      run: |
        syft ./fledge . -o spdx-json > sbom.json

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0

    - name: Sign SBOM
      env:
        COSIGN_EXPERIMENTAL: 1
      run: |
        cosign sign-blob --oidc-issuer https://token.actions.githubusercontent.com \
          --output-signature sbom.json.sig \
          --output-certificate sbom.json.crt --yes \
          sbom.json

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          myapp
          sbom.json
          sbom.json.sig
          sbom.json.crt

    - name: Verify signature (as a test)
      run: |
        cosign verify-blob \
        --certificate sbom.json.crt \
        --signature sbom.json.sig \
        --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/build-sbom-sign.yml@refs/heads/main" \
        --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
        sbom.json
