name: Build, Create SBOM, and Sign
on:
  push:
    branches: [ main ]

jobs:
  build-sbom-sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build Go binary
      run: |
        mkdir -p DEBIAN/usr/local/bin
        go build -o DEBIAN/usr/local/bin/fledge ./cmd/fledge

    - name: Install syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Create SBOM
      run: |
        mkdir DEBIAN/usr/local/share
        syft DEBIAN/usr/local/bin/fledge -o spdx-json > DEBIAN/usr/local/share/fledge-sbom.json

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0

    - name: Sign SBOM
      env:
        COSIGN_EXPERIMENTAL: 1
      run: |
        cosign sign-blob --oidc-issuer https://token.actions.githubusercontent.com \
          --bundle DEBIAN/usr/local/share/fledge-sbom.bundle \
          --yes \
          DEBIAN/usr/local/share/fledge-sbom.json
          
    - name: Generate .deb
      run: |
        dpkg-deb --build ../fledge .

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          fledge_0.1_amd64.deb

    - name: Verify signature (as a test)
      run: |
        cosign verify-blob \
        --bundle DEBIAN/usr/local/share/fledge-sbom.bundle \
        --certificate-identity "https://github.com/jordithijsman/fledge/.github/workflows/go.yml@refs/heads/main" \
        --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
        DEBIAN/usr/local/share/fledge-sbom.json
