# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  example:
    runs-on: ubuntu-latest

    permissions: {}
    env:
      GIT_HASH: ${{ github.sha }}
      GIT_VERSION: unstable
      GITHUB_RUN_ID: ${{ github.run_id }}
      GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
      KO_PREFIX: ghcr.io/${{ github.repository }}

    name: Install Cosign via go install
    steps:
      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: main
      - name: Check install!
        run: cosign version
      
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: sign blob
        run: ./scripts/sign-keyless.sh
