name: Sign README
on:
  push:
    branches: [ main ]

jobs:
  sign-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0

    - name: Sign README
      env:
        COSIGN_EXPERIMENTAL: 1
      run: |
        cosign sign-blob --oidc-issuer https://token.actions.githubusercontent.com \
          --output-signature README.md.sig \
          --output-certificate README.md.crt --yes \
          README.md
        cat README.md.crt
        cat README.md.sig

    - name: Upload signed README
      uses: actions/upload-artifact@v3
      with:
        name: signed-readme
        path: |
          README.md
          README.md.sig
          README.md.crt

#    - name: Verify signature (as a test)
#      run: |
#        cosign verify-blob \
#        --certificate README.md.crt \
#        --signature README.md.sig \
#        --certificate-identity "https://github.com/github-actions@github.com" \
#        --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
#        README.md
